cdc/urls.py
from django.conf.urls import patterns, include, url
from cdc import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^about$', views.about, name='about'),
    url(r'^testimonials$', views.testimonials, name='testimonials'),
    url(r'^form$', views.form, name='form'),
    url(r'^accounts/login$', views.login, name='login'),
    url(r'^accounts/logout$', views.logout, name='logout'),
    url(r'^accounts/home$', views.account_home, name='account'),
    url(r'^accounts/admin$', views.admin, name='admin'),
    url(r'^accounts/login/admin$', views.login_admin, name='login_admin'),
    url(r'^accounts/settings$', views.settings, name='settings'),
    url(r'^accounts/upload$', views.upload, name='upload'),
    url(r'^accounts/filings$', views.filings, name='filings'),
    url(r'^accounts/reports$', views.reports, name='reports'),
    url(r'^accounts/success$', views.success, name='success'),
)

isucdc2/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'isucdc2.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cdc.urls', namespace="cdc")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cdc/models.py
from django.db import models
from django.contrib.auth.models import User

class SiteUser(models.Model):
  def __str__(self):
    return self.company + " | " + self.user.username
  # Using a OneToOneField so we can add the extra 'company' parameter to the user
  # without extending or replacing Django's User model
  user = models.OneToOneField(User)
  company = models.CharField(default='', max_length=100)

class LoginSession(models.Model):
  def __str__(self):
    return self.token
  token = models.CharField(default='', max_length=64)
  user = models.CharField(default='', max_length=100)

class Testimonial(models.Model):
  def __str__(self):
    return self.postedby
  text = models.TextField(default='', max_length=1000)
  postedby = models.CharField(default='', max_length=1000)
  email = models.CharField(default='', max_length=100)

cdc/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

class TestimonialForm(forms.Form):
    text = forms.CharField(max_length=1000, widget=forms.Textarea)
    postedby = forms.CharField(max_length=1000)
    email = forms.CharField(max_length=100)

cdc/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from models import SiteUser, LoginSession, Testimonial
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *
from .actions import *

def index(request):
  if request.GET.get('logout', False):
    context = { 'script' : 'True' }
    return render(request, 'cdc/index.html', context)
  return render(request, 'cdc/index.html')

def contact(request):
  return render(request, 'cdc/contact.html')

def about(request):
  return render(request, 'cdc/about.html')

def testimonials(request):
  if request.GET.get('remove', False):
    entry = Testimonial.objects.get(postedby=request.GET['remove'])
    entry.delete()
  user = None
  if is_logged_in(request):
    user = get_user(request)
  return render(request, 'cdc/testimonials.html', { 'testimonials' : Testimonial.objects.all(), 'user' : user })

def login(request):
  if is_logged_in(request): # or is_admin(request):
    return HttpResponseRedirect('home')
  elif request.POST.get('next', False) and (not request.POST.get('account', False) or not request.POST.get('company', False) or not request.POST.get('pin', False)):
    context = { 'error' : "Please fill out all fields before submitting." }
    return render(request, 'cdc/login.html', context)
  elif request.POST.get('account', False) and request.POST.get('company', False) and request.POST.get('pin', False):
    # Authentication
    account = request.POST['account']
    company = request.POST['company']
    pin = request.POST['pin']
    # Make sure all POST variables are present
    if account and company and pin:
      if User.objects.filter(username=account).exists():
        siteuser = SiteUser.objects.get(company=company, user=User.objects.get(username=account))
        # if the user supplied the correct password
        if True:
          token = create_session(siteuser.user.username)
          response = HttpResponseRedirect('home')
          response.set_cookie('secret_token', token)
          return response
        else:
          context = { 'error' : "The username/password combination you entered doesn't match." }
          return render(request, 'cdc/login.html', context)
      else:
          context = { 'error' : "The user you requested was not found." }
          return render(request, 'cdc/login.html', context)
  elif request.POST.get('admin', False):
    user = get_object_or_404(User, username=request.POST.get('username', False))
    if True and user.is_superuser:
      token = create_session(user.username)
      response = HttpResponseRedirect('home')
      response.set_cookie('secret_token', token)
      return response
  else:
    return render(request, 'cdc/login.html')

def login_admin(request):
  return render(request, 'cdc/admin.html')

def settings(request):
  return render(request, 'cdc/settings.html')

def logout(request):
  response = redirect('../?logout=true')
  response.delete_cookie('secret_token')
  return response

def account_home(request):
  if is_logged_in(request):
    user = get_user(request)
    page = request.GET.get('page', False)
    success = request.GET.get('success', False)
    context = { 'user' : user, 'page' : page }
    return render(request, 'cdc/account.html', context)
  return HttpResponseRedirect('login')

def upload(request):
  user = get_user(request).username
  if request.method == 'POST':
    form = UploadFileForm(request.POST, request.FILES)
    if form.is_valid():
      handle_uploaded_file(request.FILES['file'], request.POST['title'], user)
      return HttpResponseRedirect('success')
  else:
    form = UploadFileForm()
  return render_to_response('cdc/upload.html', {'form': form})

def form(request):
  if request.method == 'POST':
    form = TestimonialForm(request.POST, request.FILES)
    entry = Testimonial(text=request.POST['text'], postedby=request.POST['postedby'])
    entry.save()
    return HttpResponseRedirect('testimonials')
  else:
    form = TestimonialForm()
  return render_to_response('cdc/form.html', {'form': form})

def success(request):
  return render(request, 'cdc/success.html')

def filings(request):
  user = get_user(request)
  files = list_files(user, '/incoming/')
  return render(request, 'cdc/files.html', { 'files' : files, 'user' : user, 'mode' : 'incoming' })

def reports(request):
  user = get_user(request)
  files = list_files(user, '/outgoing/')
  return render(request, 'cdc/files.html', { 'files' : files, 'user' : user, 'mode' : 'outgoing' })

def admin(request):
  message = ''
  files = None
  create = None
  accounts = None
  if request.GET.get('user_button', False):
    create = 'newuser'
  elif request.GET.get('admin_button', False):
    create = 'newadmin'
  # Password reset
  if request.POST.get('pwreset', False):
    user = get_object_or_404(User, username=request.POST['account'])
    user.set_password(request.POST.get('pin', False))
    user.save()
    message += 'Password successfully reset!\n'
  # Delete User
  if request.POST.get('delete', False):
    user = get_object_or_404(User, username=request.POST['account'])
    user.delete()
    message += 'User successfully deleted!\n'
  # Create new site user
  if request.POST.get('newuser', False):
    if User.objects.filter(username=request.POST.get('account', False)).exists():
      message += 'Error: User already exists in database.\n'
    else:
      user = User.objects.create_user(request.POST.get('account', False), '', request.POST.get('pin', False))
      siteuser = SiteUser(user=user, company=request.POST.get('company', False))
      siteuser.save()
      # Create the upload and download directories for the new user
      targetdir = 'uploads/' + user.username
      if not os.path.exists(targetdir):
        os.makedirs(targetdir + '/incoming')
        os.chmod(targetdir + '/incoming', 0777)
        os.makedirs(targetdir + '/outgoing')
        os.chmod(targetdir + '/outgoing', 0777)
      message += 'User successfully created!\n'
  # Create new admin
  if request.POST.get('newadmin', False):
    if User.objects.filter(username=request.POST.get('account', False)).exists():
      message += 'Error: User already exists in database.\n'
    else:
      user = User.objects.create_user(request.POST.get('username', False), '', request.POST.get('password', False))
      user.is_superuser = True
      user.save()
      siteuser = SiteUser(user=user, company="Admin")
      siteuser.save()
      message += 'Admin successfully created!\n'
  # Delete a file
  if request.GET.get('delete', False):
    try:
      os.remove(request.GET['delete'])
      message += 'File \'' + request.GET['delete'] + '\' deleted!\n'
    except OSError:
      message += 'That file does not exist.\n'
  # List a user's files
  if request.GET.get('search', False):
    files = list_files(request.GET.get('search', ''), '/' + request.GET.get('mode', ''))
    if not files:
      message += "No files found!\n"
  if request.GET.get('list_users', False):
    accounts = User.objects.all()
  if get_user(request) and get_user(request).is_superuser:
    return render(request, 'cdc/account.html', { 'users' : accounts, 'create' : create, 'message' : message, 'files' : files, 'mode' : request.GET.get('mode', False), 'search' : request.GET.get('search', False), 'user' : get_user(request) })
  return HttpResponseRedirect('login/admin')

cdc/templates/cdc/about.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block content %}
<div id="contact">
    <p><strong><i>"Robbing you one dollar at a time"</i></strong></p>
    <p>We are a company of people, working with other people. There is nothing else that we'd rather be doing. You know
    you have found the right job when it no longer feels like work. That is the environment we like to provide at
    CDC, for both our employees and clients. All work and no play is a nonexistent paradox. It is our job to do our job correctly,
    and there is hardly anything that can get in our way. That is the way it should be, and it will reign true throughout the future.</p>

    <p>If there is anything we can do to make your business better, please take some time to <a href="{% url 'cdc:contact' %}">contact us</a>.</p>
</div>
{% endblock%}

cdc/templates/cdc/account.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block title %}{% if user.is_superuser %}Admin Home{% else %}Account Home{% endif %}{% endblock %}
{% block login %}<li><a href="{% url 'cdc:logout' %}">Log Out</a></li>{% endblock %}
{% block content %}
<br/><br/>
<div id="account">
    <h2>{% if user.is_superuser %}Admin Panel -- {{ user.username }}{% else %}Welcome {{ user.siteuser.company }}!{% endif %}</h2>
    {% if user.is_superuser %}
        <p style='font-color: white'>{{ message }}</p>
        {% if create == 'newuser' %}
        <strong>New Site User</strong>
        <form action="{% url 'cdc:admin' %}" method="post">
            <input type="text" name="company" placeholder="Company Name">
            <input type="text" name="account" placeholder="Account #">
            <input type="password" name="pin" size="4" maxlength="4" placeholder="PIN">
            <input type="submit" value="Submit">
            <input type="hidden" name="newuser" value="newuser">
        </form><a href="admin"><button>Cancel</button></a></br>
        {% elif create == 'newadmin' %}
        <strong>New Admin User</strong>
        <form action="{% url 'cdc:admin' %}" method="post">
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Password">
            <input type="submit" value="Submit">
            <input type="hidden" name="newadmin" value="newadmin">
        </form>
        <a href="admin"><button>Cancel</button></a></br>
        {% else %}
        <strong>User Creation</strong>
        <form action="{% url 'cdc:admin' %}" method="get">
            <input type="submit" name="user_button" value="New User">
            <input type="submit" name="admin_button" value="New Admin">
        </form>
        {% endif %}
        <strong>PIN Reset</strong>
        <form action="{% url 'cdc:admin' %}" method="post">
            <input type="text" name="account" placeholder="Account #">
            <input type="password" name="pin" size="4" maxlength="4" placeholder="PIN">
            <input type="submit" value="Submit">
            <input type="hidden" name="pwreset" value="pwreset">
        </form>
        <strong>Delete Site User</strong>
        <form action="{% url 'cdc:admin' %}" method="post">
            <input type="text" name="account" placeholder="Account #">
            <input type="submit" value="Submit">
            <input type="hidden" name="delete" value="newuser">
        </form>
        <strong>File Admin</strong>
        <form action="{% url 'cdc:admin' %}" method="get">
            <input type="text" name="search" placeholder="Account #">
            <select name="mode">
                <option value="incoming">Filings</option>
                <option value="outgoing">Reports</option>
            </select>
            <input type="submit" value="Search">
        </form>
        {% if files %}
        <div id="files">
            <p>{{ search }}'s Files</p>
            <ol>
            {% for file in files %}
                <li><a href="/uploads/{{ search }}/{{ mode }}/{{ file }}">{{ file }}</a> <a href="?search={{ search }}&mode=incoming&delete=uploads/{{ search }}/{{ mode }}/{{ file }}" style="color: red">delete</a></li>
            {% endfor %}
            </ol>
        </div>
        {% endif %}
        {% if users %}
        <table><tr><td><u>Account</u></td><td><u>Admin</u></td></tr>
            {% for account in users %}
                <tr><td>{{ account }}</td><td>{{ account.is_superuser }}</td></tr>
            {% endfor %}
        </table>
        {% else %}
            <form action="{% url 'cdc:admin' %}" method="get">
            <input type="submit" name="list_users" value="List User Accounts">
        </form>
        {% endif %}
    {% else %}
    <div id="nav2">
        <ul>
            <li><a href="?page=upload">Upload Documentation</a></li>
            <li><a href="?page=filings">Recent Filings</a></li>
            <li><a href="?page=reports">Reports</a></li>
            <li><a href="?page=settings">Account Settings</a></li>
        </ul>
    </div>
    {% endif %}
    {% if page %}
    <h3>
        {% if page == "filings" %}
        Recent Filings
        {% elif page == "reports" %}
        Reports
        {% elif page == "upload" %}
        Upload Documentation
        {% elif page == "settings" %}
        Account Settings
        {% endif %}
    </h3>
    <iframe src="{{ page }}" seamless></iframe>
    {% endif %}
</div>
{% endblock %}

cdc/templates/cdc/admin.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block title %}Admin Login{% endblock %}
{% block content %}    <br/><br/>
    <div id="login">
        <strong><p style="text-align: center">Admin Login</p></strong>
        <form action="{% url 'cdc:login' %}" method="post"><br/>
           Username:
           <br/><input type="text" name="username"/><br/>
           Password:
           <br/><input type="password" name="password"/><br/><br/>
        <input type="submit" value="login"/>
        <input type="hidden" name="admin" value="True"/>
        <br/><br/>
            <p style="color:red">{{ error }}</p>
        </form>
    </div>
{% endblock %}

cdc/templates/cdc/base.html
<!DOCTYPE html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'cdc/style.css' %}">
    <title>
        {% block title %}Welcome to CDC!{% endblock %}
    </title>
</head>
<body>
    <div class="top">
        <header class="">
            <h1>Crippling Debt Corporation</h1>
        </header>
    </div>
    <div id="nav">
        <ul>
            <li><a href="{% url 'cdc:index' %}">Home</a></li>
            <li><a href="{% url 'cdc:testimonials' %}">Testimonials</a></li>
            <li><a href="{% url 'cdc:contact' %}">Contact Us</a></li>
            <li><a href="{% url 'cdc:about' %}">About</a></li>
            {% block login %}<li><a href="{% url 'cdc:login' %}">Log In</a></li>{% endblock %}
        </ul>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

cdc/templates/cdc/contact.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block content %}
<div id="contact">
    <h2>Contact Us</h2>
    <i>Feel free to contact us with any concerns or complaints, and we will do our best to help you.</i>
    <p><strong>Main Headquarters</strong></p>
    <p>4447 Common Ground Earth-Drive-Street Road</p>
    <p>Topoftheworld, Kansas 71423</p>
    <p>Main: (123) 456-7890</p>
    <p>Fax: (098) 765-4321</p>
    </div>
{% endblock %}

cdc/templates/cdc/files.html
<html>
    <style>
        body {
            background-color: black;
            color: white;
        }
        a {
            color: white;
        }
    </style>
    {% if files %}
    <ol>
        Files for {{ user }}
    {% for file in files %}
        <li><a href="/uploads/{{ user }}/{{ mode }}/{{ file }}">{{ file }}</a></li>
    {% endfor %}
    </ol>
    {% else %}
    <p>There are no files here yet!</p>
   {% endif %}
</html>

cdc/templates/cdc/form.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block content %}
<div id="contact">
    <form action="{% url 'cdc:form' %}" method="post">
        <p>Comments:</p><p>{{ form.text }}</p>
        <p>Your name: {{ form.postedby}}</p>
        <p>Email: {{ form.email }}</p>
        <input type="submit" value="Submit">
    </form><br/>
</div>
{% endblock %}

cdc/templates/cdc/index.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block content %}
{% if script %}
    <script>alert("You have been successfully logged out. Have a nice day!");</script>
    {% endif %}
    <div class="bar">
        <div class="section">
            This company is so great. The reason we do the things we do is because we do them, and we do them great. There is no doubt as to the excellence held within.
            Without people like this working so hard, it is not likely that others on the internet would be able to succeed. In fact, there is something about people who
            are truly capable of working this hard. It is so amazing that the foundation of the internet completely depended on their successes. With our success, people
            in the future are much more likely to become successful if they try.
        </div>
    </div>
    <script src="{% static 'cdc/jquery.min.js' %}"></script>
    <script>
        $(function() {

            $("#slideshow > div:gt(0)").hide();

            setInterval(function() {
                $('#slideshow > div:first')
                .fadeOut(1000)
                .next()
                .fadeIn(1000)
                .end()
                .appendTo('#slideshow');
            },  6000);

        });
    </script>
    <div class="center">

        <div id="slideshow">
            <div>
                <img src="{% static 'cdc/images/fountain.jpg' %}" width="100%" height="100%">
            </div>
            <div>
                <img src="{% static 'cdc/images/statue.jpg' %}" width="100%" height="100%">
            </div>
            <div>
                <img src="{% static 'cdc/images/ceiling.jpg' %}" width="100%" height="100%">
            </div>
            <div>
                <img src="{% static 'cdc/images/building.jpg' %}" width="100%" height="100%">
            </div>
        </div>
    </div>
    <div class="bar">
        <div class="section">
            Because true excellence is not to be taken for granted, it is only possible that the best of the best make it past the most complicated and challenging challenges in
            the world through hard work, perseverence, and intelligence, only to be risen above all as the sun rises unquestionably every single day of the week, month, and of course, year.
        </div>
    </div>
{% endblock %}

cdc/templates/cdc/login.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}
{% block content %}    <br/><br/>
    <div id="login">
        <form action="{% url 'cdc:login' %}" method="post"><br/>
           Company name:
            <br/><input type="text" name="company"/><br/>
           Account number:
            <br/><input type="text" name="account"/><br/>
           PIN:
           <br/><input type="password" name="pin" size="4" maxlength="4"/><br/><br/>
        <input type="submit" value="login"/>
        <input type="hidden" name="next" value="True"/>
        <br/><br/>
            <p style="color:red">{{ error }}</p>
        </form>
    </div>
{% endblock %}

cdc/templates/cdc/settings.html
<p style='color: white'>Currently, it is not possible to manage your own account on this site. Please contact an administrator for account support. We are sorry for the inconvenience.</p>

cdc/templates/cdc/success.html
<html>
    <style>
        body {
            background-color: black;
            color: white;
        }
        a {
            color: white;
        }
    </style>
    File uploaded successfully!<br/>
    <a href="{% url 'cdc:upload' %}">Upload more files</a>
    <a href="{% url 'cdc:filings' %}">View your uploaded files</a>
</html>

cdc/templates/cdc/testimonials.html
{% extends 'cdc/base.html' %}
{% load staticfiles %}

{% block content %}
<div id="contact">
    <p><a href="form">Have something positive to say? Let us know!</a></p>
    {% for entry in testimonials %}
    <p>"{{ entry.text|safe }}" --{{ entry.postedby|safe }}{% if user.is_superuser %} <a style="color: red" href="?remove={{ entry }}">delete</a>{% endif %}</p>
    {% endfor %}
</div>

{% endblock %}

cdc/templates/cdc/upload.html
<html>
    <style>
        body {
            background-color: black;
            color: white;
        }
        a {
            color: white;
        }
    </style>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.as_p }}
    <input type='submit' value='Upload'>
</form>
</html>